# Generated by Django 4.0.3 on 2022-03-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_playlist_next_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='films',
        ),
        migrations.CreateModel(
            name='PlaylistFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.film')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playlist')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
