# Generated by Django 4.0.3 on 2022-03-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_remove_playlist_films_playlistfilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='films',
            field=models.ManyToManyField(through='player.PlaylistFilm', to='player.film'),
        ),
    ]
