# Generated by Django 4.0.3 on 2022-03-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_alter_stream_options_stream_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='active_film',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='next_film',
        ),
        migrations.AddField(
            model_name='playlist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
