# Generated by Django 4.0.3 on 2022-04-24 09:49

from django.db import migrations


def add_default_stream(apps, schema_editor):
    Stream = apps.get_model('player', 'Stream')

    Stream.objects.create(name='Default stream', 
            url='rtmp://streamer/live/mystream', 
            active=True,
            link='http://localhost:8081/video.html')
            
    Stream.objects.create(name='Test stream', 
            url='rtmp://streamer/live/testing', 
            active=True,
            link='http://localhost:8081/video.html#testing')            

class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_remove_playlist_active_film_and_more'),
    ]

    operations = [
        migrations.RunPython(add_default_stream),
    ]
