# Generated by Django 4.0.3 on 2022-05-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_auto_20220424_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='font_size',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
