# Generated by Django 4.0.3 on 2022-06-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_film_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='videodata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='subtitle',
            field=models.FileField(blank=True, help_text='Subtitle file', null=True, upload_to='subtitles'),
        ),
        migrations.AlterField(
            model_name='film',
            name='use_subtitle_in_video',
            field=models.BooleanField(default=False, help_text='Use embedded subtitle track in video file'),
        ),
    ]
