# Generated by Django 4.0.3 on 2022-06-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_film_videodata_alter_film_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('index', models.IntegerField(default=0)),
                ('language', models.CharField(default='', max_length=255)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='audio_stream',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'audio'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.filmstream'),
        ),
        migrations.AddField(
            model_name='film',
            name='subtitle_stream',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'subtitle'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.filmstream'),
        ),
    ]
