# Generated by Django 3.2.6 on 2022-12-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_filmstream_film_audio_stream_film_subtitle_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='use_subtitle_in_video',
        ),
        migrations.AddField(
            model_name='filmstream',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='audio_stream',
            field=models.ForeignKey(blank=True, help_text='Audio Stream', limit_choices_to={'type': 'audio'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.filmstream'),
        ),
        migrations.AlterField(
            model_name='film',
            name='subtitle',
            field=models.FileField(blank=True, help_text='External Subtitle file', null=True, upload_to='subtitles'),
        ),
        migrations.AlterField(
            model_name='film',
            name='subtitle_stream',
            field=models.ForeignKey(blank=True, help_text='Embedded subtitle track', limit_choices_to={'type': 'subtitle'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.filmstream'),
        ),
    ]
