# Generated by Django 3.2.6 on 2023-01-29 01:03

from django.db import migrations, models
import django.db.models.deletion

def add_default_stream_settings(apps, schema_editor):
    Stream = apps.get_model('player', 'StreamSetting')

    Stream.objects.create(name='Default settings')
        

class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20221202_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video_codec', models.CharField(choices=[('libx264', 'libx264'), ('libx265', 'libx265'), ('libvpx-vp9', 'libvpx-vp9')], default='libx264', max_length=255)),
                ('audio_codec', models.CharField(choices=[('aac', 'aac'), ('libmp3lame', 'libmp3lame'), ('libopus', 'libopus')], default='aac', max_length=255)),
                ('reduce_scale', models.IntegerField(default='1280', help_text='Reduce scale to this value if video is larger. Set to 0 to disable.', max_length=255)),
                ('video_profile', models.CharField(choices=[('baseline', 'baseline'), ('main', 'main'), ('high', 'high'), ('high10', 'high10'), ('high422', 'high422'), ('high444', 'high444')], default='baseline', max_length=255)),
                ('encoding_preset', models.CharField(choices=[('ultrafast', 'ultrafast'), ('superfast', 'superfast'), ('veryfast', 'veryfast'), ('faster', 'faster'), ('fast', 'fast'), ('medium', 'medium'), ('slow', 'slow'), ('slower', 'slower'), ('veryslow', 'veryslow')], default='medium', max_length=255)),
                ('crf', models.IntegerField(default=23, help_text='Constant Rate Factor (0-51, lower is better quality but higher bitrate)')),
                ('audio_bitrate', models.IntegerField(default=192)),
                ('video_max_bitrate', models.IntegerField(default=5000, help_text='Maximum video bitrate in kbps')),
                ('video_buffer_size', models.IntegerField(default=10000, help_text='Video buffer size in kbps')),
                ('video_tune', models.CharField(choices=[('Off', 'Off'), ('film', 'film'), ('animation', 'animation'), ('grain', 'grain'), ('stillimage', 'stillimage'), ('psnr', 'psnr'), ('ssim', 'ssim'), ('fastdecode', 'fastdecode'), ('zerolatency', 'zerolatency')], default='Off', max_length=255)),
                ('normalize_volume', models.BooleanField(default=True)),
                ('keyframe_interaval', models.IntegerField(default=30)),
                ('output_format', models.CharField(choices=[('flv', 'flv'), ('mp4', 'mp4'), ('webm', 'webm')], default='flv', max_length=255)),
            ],
        ),
        migrations.RunPython(add_default_stream_settings),    
        migrations.AddField(
            model_name='film',
            name='video_tune_override',
            field=models.CharField(choices=[('Off', 'Off'), ('film', 'film'), ('animation', 'animation'), ('grain', 'grain'), ('stillimage', 'stillimage'), ('psnr', 'psnr'), ('ssim', 'ssim'), ('fastdecode', 'fastdecode'), ('zerolatency', 'zerolatency')], default='Off', max_length=255),
        ),
        migrations.AddField(
            model_name='film',
            name='workaround_for_10bit_hevc',
            field=models.BooleanField(default=False, help_text='Workaround for 10bit HEVC streams. Handles playback of them but might impact video quality.'),
        ),
        migrations.AddField(
            model_name='stream',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='player.streamsetting'),
            preserve_default=False,
        ),
    ]
