# Generated by Django 3.2.6 on 2023-01-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_auto_20230129_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamsetting',
            name='audio_channels',
            field=models.IntegerField(default=2),
        ),
    ]
