# Generated by Django 3.2.6 on 2023-01-29 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_streamsetting_audio_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='linked_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_from', to='player.playlist'),
        ),
        migrations.AlterField(
            model_name='streamsetting',
            name='reduce_scale',
            field=models.IntegerField(default='1280', help_text='Reduce scale to this value if video is larger. Set to 0 to disable.'),
        ),
    ]
