# Generated by Django 3.2.6 on 2023-01-29 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_film_volume_normalization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='repeat',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='linked_to',
            field=models.ForeignKey(blank=True, help_text='If set, start playing linked playlist after this', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_from', to='player.playlist'),
        ),
    ]
