# Generated by Django 3.2.6 on 2023-03-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0016_auto_20230129_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamsetting',
            name='fast_decode',
            field=models.BooleanField(default=False, help_text='disables CABAC and the in-loop deblocking filter to allow for faster decoding on devices with lower computational power.'),
        ),
        migrations.AddField(
            model_name='streamsetting',
            name='zero_latency',
            field=models.BooleanField(default=True, help_text='Optimization for fast encoding and low latency streaming'),
        ),
        migrations.AlterField(
            model_name='film',
            name='video_tune_override',
            field=models.CharField(choices=[('Off', 'Off'), ('film', 'film'), ('animation', 'animation'), ('grain', 'grain'), ('stillimage', 'stillimage')], default='Off', max_length=255),
        ),
        migrations.AlterField(
            model_name='streamsetting',
            name='video_tune',
            field=models.CharField(choices=[('Off', 'Off'), ('film', 'film'), ('animation', 'animation'), ('grain', 'grain'), ('stillimage', 'stillimage')], default='Off', max_length=255),
        ),
    ]
