# Generated by Django 4.0.3 on 2023-12-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0017_auto_20230302_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='for_guild_movie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='font_size',
            field=models.PositiveIntegerField(default=23, help_text='Subtitle font size'),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.FileField(help_text='Video file', max_length=255, upload_to='videos'),
        ),
    ]
