# Generated by Django 4.0.3 on 2023-12-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0018_playlist_for_guild_movie_alter_film_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='subtitle',
            field=models.FileField(blank=True, help_text='External Subtitle file', max_length=255, null=True, upload_to='subtitles'),
        ),
    ]
