# Generated by Django 4.0.3 on 2023-12-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0019_alter_film_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmstream',
            name='special',
            field=models.CharField(blank=True, choices=[('before_mainmovie', 'before_mainmovie'), ('after_mainmovie', 'after_mainmovie')], max_length=255, null=True),
        ),
    ]
