# Generated by Django 4.2.8 on 2026-01-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0022_film_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='autostart_playlist',
            field=models.ForeignKey(blank=True, help_text='Playlist to automatically start playing on server startup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autostart_for_streams', to='player.playlist'),
        ),
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('scanning', 'Scanning'), ('processed', 'Processed')], default='new', max_length=255),
        ),
        migrations.AlterField(
            model_name='stream',
            name='active_playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_streams', to='player.playlist'),
        ),
    ]
